BACKGROUND_SOUND = r'files\sounds\background.ogg'
BUTTON_SOUND = r'files\sounds\button.ogg'
REDIRECT_SOUND = r'files\sounds\direction4.ogg'
EAT_SOUND = r'files\sounds\eat.ogg'
WINDOW_TITLE: str = 'Snake'
