DIR_UP: int = 0
DIR_DOWN: int = 1
DIR_LEFT: int = 2
DIR_RIGHT: int = 3
HEAD_DIRECTIONS = {DIR_UP: 0, DIR_RIGHT: 270, DIR_DOWN: 180, DIR_LEFT: 90}

STARTER_SIZE: int = 4
MOVEMENT_COUNTER = 5

BATTLE_TIMER = 60
SURVIVAL_TIMER = 20
